# Generated by Django 3.0.6 on 2020-05-25 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0002_auto_20200525_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
