# Generated by Django 3.0.6 on 2020-05-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0003_auto_20200525_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.TextField(verbose_name='Дата публикации'),
        ),
    ]
