# Generated by Django 3.0.6 on 2020-05-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0005_auto_20200525_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(unique=True, verbose_name='Ссылка на объявление'),
        ),
    ]
