# Generated by Django 3.0.6 on 2020-05-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0007_auto_20200526_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.PositiveIntegerField(verbose_name='Адрес'),
        ),
    ]
