# Generated by Django 3.0.6 on 2020-05-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0008_auto_20200526_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
    ]
