# Generated by Django 3.0.6 on 2020-05-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0012_auto_20200527_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя пользователя'),
        ),
    ]
