# Generated by Django 3.0.6 on 2020-06-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0014_auto_20200527_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('srok', models.TextField(verbose_name='Срок')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на объявление')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренда',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Купить', 'verbose_name_plural': 'Купить'},
        ),
    ]
